# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Inline-Java
version:      0.52
version_from: Java.pm
installdirs:  site
requires:
    Inline:                        0.44
    MIME::Base64:                  0
    Test:                          1.13

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
